steps:
  - id: "terraform plan"
    name: 'alpine/terragrunt'
    args: ['terragrunt', 'run-all', 'plan']
    dir : './src/data-only_modules/secret'
    env:
      - "TF_VAR_project=$PROJECT_ID"

  - id: "terraform apply"
    name: 'alpine/terragrunt'
    args: ['terragrunt', 'run-all', 'apply', '--terragrunt-non-interactive']
    dir : './src/data-only_modules/secret'
    env:
      - "TF_VAR_project=$PROJECT_ID"
